apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels: 
    app: wordpress-app
    tier: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: k8
        image: anil132/k8s
        ports:
        - containerPort: 90
